name: template-sync

on:
  push:

  pull_request: # run on pull requests to preview changes before applying

  workflow_run: # setup this workflow as a dependency of others
    workflows: [ test, release ] # don't sync template unless tests and other important workflows have passed

jobs:
  template-sync:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-workflow-run-wait@v1.4.2 # wait for workflow_run to be successful
      - uses: ahmadnassri/action-workflow-queue@v1.0.1 # avoid conflicts, by running this template one at a time
      - uses: ahmadnassri/action-template-repository-sync@v2.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
